# Generated by Django 3.2.6 on 2022-05-23 15:08

import aeroflot.models
import django.core.validators
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_image', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_ai)),
            ],
            options={
                'verbose_name': 'Aircraft Type Image',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(editable=False, max_length=100, unique=True)),
                ('route', models.CharField(help_text='Example: TOKNU L4 NUDKO T561 ODATI T875 GENPA', max_length=4000, verbose_name='Route')),
                ('flight_level', models.IntegerField(help_text='Example: 370', verbose_name='Flight Level')),
                ('distance', models.IntegerField(blank=True, help_text="Example: 350 in NM. It'll be calculated automatically if it'll be clear.", null=True, verbose_name='Distance')),
                ('deptime', models.TimeField(blank=True, help_text='Example: 11:00', null=True, verbose_name='Departure Time')),
                ('flight_time', models.TimeField()),
                ('flight_type', models.CharField(blank=True, editable=False, max_length=100)),
                ('pax', models.IntegerField(blank=True, null=True)),
                ('cargo', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('altitude', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Aeroflot', max_length=10)),
                ('callsign', models.CharField(blank=True, max_length=100, null=True)),
                ('icao', models.CharField(default='AFL', max_length=10)),
                ('iata', models.CharField(default='SU', max_length=10)),
                ('hub', models.CharField(default='UUEE', max_length=10)),
                ('logo', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_company)),
                ('hours', models.IntegerField(default=0, editable=0)),
                ('flights', models.IntegerField(default=0, editable=0)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_registration', models.CharField(max_length=10, unique=True, verbose_name='Aircraft Registration')),
                ('aircraft_image', models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_fleet)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Stored', 'Stored'), ('Retro', 'Retro')], default='Inactive', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Fleet',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightnum', models.CharField(blank=True, help_text='Example: SU123', max_length=100, null=True, verbose_name='Flight Number')),
                ('callsign', models.CharField(blank=True, help_text='Example: AFL123', max_length=100, null=True, verbose_name='Callsign')),
                ('aircraft_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aircraft Type')),
                ('aircraft_registration', models.CharField(blank=True, max_length=10, null=True, verbose_name='Aircraft Registration')),
                ('dep_time', models.DateTimeField(blank=True, help_text='Example: 11:00', null=True, verbose_name='Departure Time')),
                ('arr_time', models.DateTimeField(blank=True, help_text='Example: 11:00', null=True, verbose_name='Arrival Time')),
                ('flight_time', models.IntegerField(blank=True, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('route', models.CharField(help_text='Example: TOKNU L4 NUDKO T561 ODATI T875 GENPA', max_length=4000, null=True, verbose_name='Route')),
                ('pax', models.IntegerField(null=True)),
                ('cargo', models.IntegerField(null=True)),
                ('landing_vs', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, default=100, null=True)),
                ('fuel_used', models.IntegerField(blank=True, default=0, null=True)),
                ('fuel_left', models.IntegerField(blank=True, default=0, null=True)),
                ('zfw', models.IntegerField(blank=True, default=0, null=True)),
                ('to_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('landing_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('fsuipc_data', models.JSONField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text_ru', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(default='AFL', max_length=10)),
                ('status', models.CharField(choices=[('Just Registred', 'Just Registred'), ('Inactive', 'Inactive'), ('Active', 'Active')], default='Just Registred', max_length=100)),
                ('additional_flights', models.IntegerField(default=0)),
                ('additional_hours', models.IntegerField(default=0, help_text='IN SECONDS!!! CONVERT HOURS TO SECONDS!!! For Example 2 hours = 7200 seconds')),
            ],
            options={
                'verbose_name_plural': 'Pilots',
            },
        ),
        migrations.CreateModel(
            name='RecalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '7. Recalculate All Flights and Hours',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightnum', models.CharField(help_text='Example: SU123', max_length=100, unique=True, verbose_name='Flight Number')),
                ('callsign', models.CharField(help_text='Example: AFL123', max_length=100, verbose_name='Callsign')),
                ('route', models.CharField(help_text='Example: TOKNU L4 NUDKO T561 ODATI T875 GENPA', max_length=4000, verbose_name='Route')),
                ('flight_level', models.IntegerField(help_text='Example: 370', verbose_name='Flight Level')),
                ('distance', models.IntegerField(blank=True, help_text="Example: 350 in NM. It'll be calculated automatically if it'll be clear.", null=True, verbose_name='Distance')),
                ('deptime', models.TimeField(blank=True, help_text='Example: 11:00', null=True, verbose_name='Departure Time')),
                ('arrtime', models.TimeField(blank=True, help_text='Example: 12:00', null=True, verbose_name='Arrival Time')),
                ('flights', models.IntegerField(default=0, editable=False)),
                ('hours', models.FloatField(default=0, editable=False)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=100)),
                ('flight_type', models.CharField(choices=[('Regular', 'Regular'), ('Fly-In', 'Fly-In'), ('Charter', 'Charter')], default='Regular', max_length=100)),
                ('payload_percentage', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Schedule',
            },
        ),
    ]
