# Generated by Django 3.2.6 on 2022-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='fsuipc_data',
            field=models.JSONField(null=True),
        ),
    ]
