# Generated by Django 3.2.6 on 2022-02-07 11:58

import aeroflot.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0002_flight_fsuipc_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftimage',
            name='aircraft_image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_fleet),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_company),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='aircraft_image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_fleet),
        ),
    ]
