# Generated by Django 3.2.6 on 2022-05-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0003_alter_pilot_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight', to='aeroflot.company'),
        ),
    ]
