# Generated by Django 3.2.6 on 2022-02-07 20:13

import aeroflot.models
from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0003_auto_20220207_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraftimage',
            options={'verbose_name': 'Aircraft Type Image'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='fleet',
            options={'verbose_name_plural': 'Fleet'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name_plural': 'Flight'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='pilot',
            options={'verbose_name_plural': 'Pilots'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name_plural': 'Schedule'},
        ),
        migrations.AlterField(
            model_name='aircraftimage',
            name='aircraft_image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_ai),
        ),
    ]
