# Generated by Django 3.2.6 on 2022-05-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0004_alter_flight_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
