# Generated by Django 3.2.6 on 2022-02-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0004_auto_20220207_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name_plural': 'Flights'},
        ),
    ]
