# Generated by Django 3.2.6 on 2022-05-29 18:57

import aeroflot.models
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0005_schedule_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='schedule',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book', to='aeroflot.schedule'),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='aircraft_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=aeroflot.models.get_file_path_fleet),
        ),
    ]
