# Generated by Django 3.2.6 on 2022-02-07 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0005_auto_20220207_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight', to='aeroflot.pilot'),
        ),
    ]
