# Generated by Django 3.2.6 on 2022-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0006_alter_flight_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cargo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
