# Generated by Django 3.2.6 on 2022-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroflot', '0007_auto_20220207_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(help_text='Example: TOKNU L4 NUDKO T561 ODATI T875 GENPA', max_length=4000, null=True, verbose_name='Route'),
        ),
    ]
