version: '3'
services:
  db:
    image: kartoza/postgis
    environment:
      - POSTGRES_DB=aflva
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=citext,
      - TZ=Europe/Moscow
    ports:
       - "5430:5432"
    volumes:
      - ./postgres-install-extensions.sh:/docker-entrypoint-initdb.d/postgres-install-extensions.sh
  redis:
    image: redis
    ports:
       - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=vhost
    ports:
      - "15671:15672"
      - "5671:5672"
#  s3:
#      image: minio/minio
#      ports:
#        - "9000:9000"
#        - "9001:9001"
#      volumes:
#        - ./storage/minio:/data
#      environment:
#        MINIO_ACCESS_KEY: minio_access_key
#        MINIO_SECRET_KEY: minio_secret_key
#        MINIO_BUCKET: bucket
#        MINIO_ROOT_USER: minio_access_key
#        MINIO_ROOT_PASSWORD: minio_secret_key
#      command: server --console-address ":9001" /data
#  createbuckets:
#      image: minio/mc
#      depends_on:
#        - s3
#      entrypoint: >
#        /bin/sh -c "
#        /usr/bin/mc alias set myminio http://s3:9000 minio_access_key minio_secret_key --api S3v4;
#        /usr/bin/mc mb myminio/bucket;
#        /usr/bin/mc policy set public myminio/bucket;
#        exit 0;
#        "
#  flower:
#    platform: linux/amd64
#    image: mher/flower
#    environment:
#      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@127.0.0.1:5671/vhost
#      - FLOWER_PORT=8888
#    ports:
#     - 8888:8888
