# Generated by Django 3.2.6 on 2022-05-23 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_version', models.CharField(help_text='Example: 1.0.1', max_length=20, verbose_name='DEVELOPER ONLY! Agent Version')),
                ('agent_file', models.FileField(upload_to='', verbose_name='DEVELOPER ONLY! Agent File')),
            ],
            options={
                'verbose_name': 'DEVELOPER ONLY! Agent',
            },
        ),
        migrations.CreateModel(
            name='AircraftICAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_icao', models.CharField(help_text='Example: A319', max_length=10, unique=True, verbose_name='Aircraft ICAO Code')),
                ('flaps10', models.IntegerField(help_text='Example: 230 in knots', verbose_name='Flaps 10° Speed')),
                ('flaps15', models.IntegerField(help_text='Example: 200 in knots', verbose_name='Flaps 15° Speed')),
                ('flaps35', models.IntegerField(help_text='Example: 177 in knots', verbose_name='Flaps 35° Speed')),
                ('gear_up', models.IntegerField(help_text='Example: 260 in knots', verbose_name='Vmax Gear Up')),
                ('gear_down', models.IntegerField(help_text='Example: 230 in knots', verbose_name='Vmax Gear Down')),
                ('gear_cruise', models.IntegerField(help_text='Example: 300 in knots', verbose_name='Vmax Gear Cruise')),
                ('max_pitch', models.FloatField(help_text='Example: 15 in °', verbose_name='Max Pitch')),
            ],
            options={
                'verbose_name': 'Aircraft Type',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Example: Perfect Landing', max_length=100, null=True, verbose_name='Penalty Name En')),
                ('name_ru', models.CharField(blank=True, help_text='Example: Отличная Посадка', max_length=100, null=True, verbose_name='Penalty Name Rus')),
                ('rate', models.IntegerField(help_text='Example: 10 or -10 ...', verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='SimVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_exe', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('flights', models.IntegerField(default=0, editable=False, verbose_name='Flights')),
                ('hours', models.FloatField(default=0, editable=False, verbose_name='Hours')),
                ('now', models.CharField(blank=True, help_text='Airport ICAO Code', max_length=4, null=True)),
                ('ivaoid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Ivao ID')),
                ('vatsimid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Vatsim ID')),
                ('telegram_chat_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
        ),
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_name', models.CharField(help_text='Example: Airbus A319-114', max_length=20, unique=True, verbose_name='Aircraft Name')),
                ('aircraft_plan_suffix', models.CharField(choices=[('/H', '/H'), ('/W', '/W'), ('/Z', '/Z'), ('/L', '/L'), ('/X', '/X'), ('/T', '/T'), ('/U', '/U'), ('/D', '/D'), ('/B', '/B'), ('/A', '/A'), ('/M', '/M'), ('/N', '/N'), ('/P', '/P'), ('/Y', '/Y'), ('/C', '/C'), ('/I', '/I'), ('/V', '/V'), ('/S', '/S'), ('/G', '/G')], help_text='Example: /L', max_length=20, verbose_name='Equipment Suffix')),
                ('engine_type', models.CharField(help_text='Example: CFM56-5B5/P', max_length=20, verbose_name='Engine Type')),
                ('flight_range', models.IntegerField(help_text='Example: 3700 in NM', verbose_name='Max Range')),
                ('max_flightlevel', models.IntegerField(help_text='Example: 380 in FL', verbose_name='Max Flight Level')),
                ('cruise_speed', models.IntegerField(help_text='Example: 455 in knots', verbose_name='Cruise Speed')),
                ('empty_weight', models.IntegerField(help_text='Example: 41513 in KGS', verbose_name='Empty Weight')),
                ('max_weight', models.IntegerField(help_text='Example: 70400 in KGS', verbose_name='Max Weight')),
                ('landing_weight', models.IntegerField(help_text='Example: 61000 in KGS', verbose_name='Landing Weight')),
                ('fuel', models.IntegerField(help_text='Example: 61000 in KGS', verbose_name='Fuel Load')),
                ('payload', models.IntegerField(help_text='Example: 15500 in KGS', verbose_name='Payload')),
                ('pax', models.IntegerField(help_text='Example: 150', verbose_name='Pax')),
                ('aircraft_icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_type', to='main.aircrafticao', verbose_name='Aircraft ICAO Code')),
            ],
            options={
                'verbose_name': 'Aircraft Type',
            },
        ),
    ]
