# Generated by Django 3.2.6 on 2022-02-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircrafticao',
            options={'verbose_name': 'Aircraft Type'},
        ),
    ]
