# Generated by Django 3.2.6 on 2022-05-22 17:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
    ]
