# Generated by Django 3.2.6 on 2022-05-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='now',
            field=models.CharField(blank=True, help_text='Airport ICAO Code', max_length=4, null=True),
        ),
    ]
